----------- CREATE TABLES -----------
-- TABLA USERS --

CREATE TABLE USERS (
	USR_ID INT PRIMARY KEY AUTO_INCREMENT,
	USR_NOMBRE VARCHAR(30) NOT NULL,
	USR_EMAIL VARCHAR(30) NOT NULL UNIQUE KEY,	
	USR_PASSWORD VARCHAR(30) NOT NULL,
	USR_PAIS_ORIGEN VARCHAR(30) NOT NULL,	
	USR_PARTIDAS_JUGADAS INT NOT NULL,
	USR_CAMPEONATOS_JUGADOS INT NOT NULL,
	USR_PARTIDAS_GANADAS INT NOT NULL,
	USR_PUNTOS_GANADOS INT NOT NULL,
	USR_FECHA_DESBLOQ DATE
);

-- TABLA USERS --

CREATE TABLE CAMPEONATOS(
	CAMP_ID INT PRIMARY KEY AUTO_INCREMENT,
	CAMP_FECHA_COMIENZO DATE NOT NULL,
	CAMP_TOTAL_INSCRIPTORES INT NOT NULL,
	CAMP_PUNTOS_GANADOS INT NOT NULL,
	CAMP_NOMBRE_CAMPEONATO VARCHAR(50) NOT NULL,
	CAMP_USR_CREADOR_CAMP FOREIGN KEY USR_ID REFERENCES USERS,
	CAMP_FECHA_FINALIZACION DATE,
	CAMP_NUM_USR_BLOQUEDOS INT
);

-- FICHAS --

CREATE TABLE FICHAS(
	FICHA_CODIGO INT PRIMARY KEY AUTO_INCREMENT,
	FICHA_COLOR INT NOT NULL,
	FICHA_NUMERO INT NOT NULL
);

-- PARTECIPANTES CAMPEONATP --

CREATE TABLE PTC_ID(
	PTC_ID INT PRIMARY KEY AUTO_INCREMENT,
	PTC_CAMP_ID FOREIGN KEY CAMP_ID REFERENCES CAMPEONATOS,
	PTC_USR_ID FOREIGN KEY USR_ID REFERENCES USERS,
	PTC_USER_GANADOR_SN BOOL, 
);

-- PARTIDAS_CAMPEONATOS --
CREATE TABLE PARTIDAS_CAMPEONATOS(
	PAC_ID INT PRIMARY KEY AUTO_INCREMENT,
	PAC_CAMP_ID FOREIGN KEY CAMP_ID REFERENCES CAMPEONATOS,
	PAC_NIVEL INT NOT NULL,
	PAC_FECHA DATE
);

-- PARTIC_Partidas_camp --
CREATE TABLE PARTIC_PARTIDAS_CAMP(
	PPC_PTC
);