-- --------- CREATE TABLES -----------
-- USUARIOS --
/*
CREATE TABLE USUARIOS (
	USR_ID INT PRIMARY KEY AUTO_INCREMENT,
	USR_NOMBRE VARCHAR(30) NOT NULL,
	USR_EMAIL VARCHAR(30) NOT NULL UNIQUE KEY,	
	USR_PASSWORD VARCHAR(30) NOT NULL,
	USR_PAIS_ORIGEN VARCHAR(30) NOT NULL,	
	USR_PARTIDAS_JUGADAS INT NOT NULL,
	USR_CAMPEONATOS_JUGADOS INT NOT NULL,
	USR_PARTIDAS_GANADAS INT NOT NULL,
	USR_PUNTOS_GANADOS INT NOT NULL,
	USR_FECHA_DESBLOQ DATE
);

-- CAMPEONATOS --

CREATE TABLE CAMPEONATOS(
	CAMP_ID INT PRIMARY KEY AUTO_INCREMENT,
	CAMP_FECHA_COMIENZO DATE NOT NULL,
	CAMP_TOTAL_INSCRIPTORES INT NOT NULL,
	CAMP_PUNTOS_GANADOS INT NOT NULL,
	CAMP_NOMBRE_CAMPEONATO VARCHAR(50) NOT NULL,
	CAMP_USR_CREADOR_CAMP INT,
	CAMP_FECHA_FINALIZACION DATE,
	CAMP_NUM_USR_BLOQUEDOS INT,
	
	FOREIGN KEY (CAMP_USR_CREADOR_CAMP) REFERENCES USUARIOS (USR_ID)
);

-- FICHAS --

CREATE TABLE FICHAS(
	FICHA_CODIGO INT PRIMARY KEY AUTO_INCREMENT,
	FICHA_COLOR INT NOT NULL,
	FICHA_NUMERO INT NOT NULL
);

-- PARTECIPANTES CAMPEONATP --
*/
CREATE TABLE PARTICIPANTES_CAMPEONATOS(
	PTC_ID INT PRIMARY KEY AUTO_INCREMENT,
	PTC_CAMP_ID INT, 
	PTC_USR_ID INT,
	PTC_USER_GANADOR_SN BOOL,
	
	FOREIGN KEY (PTC_CAMP_ID) REFERENCES CAMPEONATOS(CAMP_ID),
 	FOREIGN KEY (PTC_USR_ID) REFERENCES USUARIOS(USR_ID)
);
/*
-- PARTIDAS_CAMPEONATOS --
CREATE TABLE PARTIDAS_CAMPEONATOS(
	PAC_ID INT PRIMARY KEY AUTO_INCREMENT,
	PAC_CAMP_ID INT,
	PAC_NIVEL INT NOT NULL,
	PAC_FECHA DATE,
	
	FOREIGN KEY (PAC_CAMP_ID) REFERENCES CAMPEONATOS(CAMP_ID)
);

-- PARTIC_Partidas_camp --
CREATE TABLE PARTIC_PARTIDAS_CAMP(
	PPC_PTC_ID INT,	-- PK
	PPC_PAC_ID INT,	-- PK
	PPC_PUNTOS_OBTENIDOS INT NOT NULL,
	PPC_POSICION_PARTIDA INT,
	
	FOREIGN KEY (PPC_PTC_ID) REFERENCES PARTICIPANTES_CAMPEONATOS(PTC_ID),
	FOREIGN KEY (PPC_PAC_ID) REFERENCES PARTIDAS_CAMPEONATOS(PAC_ID),
	
	PRIMARY KEY (PPC_PTC_ID, PPC_PAC_ID)
);

-- POSICION_TABLERO_CAMPEONATO --
CREATE TABLE POSICION_TABLERO_CAMPEONATO(
	PTC_ID INT PRIMARY KEY AUTO_INCREMENT,
	PTC_PAC_ID INT,
	PTC_FICHA_ID INT,
	PTC_FICHA_POSX FLOAT NOT NULL,
	PTC_FICHA_POSY FLOAT NOT NULL,
	PTC_PTC_ID INT,
	PTC_PAC_ID_2 INT, 

	FOREIGN KEY (PTC_PAC_ID) REFERENCES PARTICIPANTES_CAMPEONATOS(PTC_ID),
	FOREIGN KEY (PTC_FICHA_ID) REFERENCES fichas(FICHA_CODIGO),
 	FOREIGN KEY (PTC_PTC_ID) REFERENCES PARTICIPANTES_CAMPEONATOS(PTC_ID),
	FOREIGN KEY (PTC_PAC_ID_2) REFERENCES PARTIDAS_CAMPEONATOS(PAC_ID)
);

-- CONFIG_PARTIDAS --
CREATE TABLE CONFIG_PARTIDAS(
	CP_ID INT PRIMARY KEY AUTO_INCREMENT,
	CP_TIEMPO_ESPERA FLOAT NOT NULL,
	CP_NUM_PARTICIPANTES INT NOT NULL,
	CP_PUNTOS_GANADOR INT NOT NULL,
	CP_NOMBRE_CONFIG VARCHAR(20) NOT NULL
);

-- PARTIDAS --
CREATE TABLE PARTIDAS(
	PART_ID INT PRIMARY KEY AUTO_INCREMENT,
	PART_FECHA_HORA_INICIO DATETIME NOT NULL,
	PART_FECHA_HORA_FIN DATETIME,
	PART_ID_CONFIG_PART INT,
	PART_ESTADO INT,		-- 0 pause 1 ended
	PART_TURNO_USUARIO INT,
	
	FOREIGN KEY (PART_ID_CONFIG_PART) REFERENCES CONFIG_PARTIDAS(CP_ID)
);

-- PARTIDAS_USUARIOS --
CREATE TABLE PARTIDAS_USUARIOS(
	PU_PART_ID INT, 	-- PK
	PU_USR_ID INT,	 	-- PK
	PU_PUNTOS_OBTENIDOS INT NOT NULL,
	PU_POSICION_FINAL_EN_PARTIDA INT,
	PU_POSICION_EN_TABLERO int,
	
	FOREIGN KEY (PU_PART_ID) REFERENCES PARTIDAS(PART_ID),
	FOREIGN key (PU_USR_ID) REFERENCES USUARIOS(USR_ID),
	
	PRIMARY KEY (PU_PART_ID, PU_USR_ID)
);

-- POSICION_TABLERO --
CREATE TABLE POSICION_TABLERO(
	PT_ID INT PRIMARY KEY AUTO_INCREMENT,
	PT_PART_ID INT,
	PT_FICHA_ID INT,
	PT_FICHA_POSX FLOAT NOT NULL,
	PT_FICHA_POSY FLOAT NOT NULL,
	PT_PU_PART_ID INT,
	PT_PU_USR_ID INT,

	FOREIGN KEY (PT_PART_ID) REFERENCES PARTIDAS(PART_ID),
	FOREIGN KEY (PT_FICHA_ID) REFERENCES FICHAS(FICHA_CODIGO),
	FOREIGN KEY (PT_PU_PART_ID) REFERENCES PARTIDAS_USUARIOS(PU_PART_ID),
	FOREIGN KEY (PT_PU_USR_ID) REFERENCES PARTIDAS_USUARIOS(PU_USR_ID)
);*/